#!/bin/bash
#
# exit with a negative number

command="exit betty123"
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell
rm -f $tmp_file

# create a pseudo random file
touch $tmp_file
# send commands
echo "$command" | $SHELL 2> $OUTPUTFILE &

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
nmatch=`cat $OUTPUTFILE | grep -c ": 1: exit: Illegal number: betty123"`
if [ $nmatch -eq 1 ]; then
	    print_ok
else
	    print_ko
fi

# clean up
stop_shell
rm -f $tmp_file
