#!/bin/bash
#
# test simple command /bin/ls

command="cd /tmp
cd /usr
cd -"

# clean up
stop_shell

# create a pseudo random file
# run command
export OLDPWD=""
echo "$command" | $SHELL > $OUTPUTFILE 2> /dev/null &

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
nmatch=`cat $OUTPUTFILE | grep -c "/tmp"`
if [ $nmatch -eq 1 ]; then
      print_ok
else
	   print_ko
fi

# clean up
stop_shell
