#!/bin/bash
#
# simple test to check if for white spaces and tabs

command="    ls			\t   	\t -l \t	"
tmp_file="checker_tmp_file_$RANDOM"
save_file=`echo $BASH_SOURCE | sed -e 's/\.\///g' -e 's/\//#/g'`

# clean up
stop_shell
rm -f $tmp_file

# create a pseudo random file
touch $tmp_file
# send commands
printf "$command\n" | $SHELL > $OUTPUTFILE 2> /dev/null &

# wait a little bit
$SLEEP $SLEEPSECONDS

# copy saved output for debugging
# cat $OUTPUTFILE > "/home/vagrant/simple_shell/simple_shell_test_suite/your_output"

# check the result
nmatch=`cat $OUTPUTFILE | grep -c "$tmp_file"`
if [ $nmatch -eq 1 ]; then
	   print_ok
else
	   print_ko
fi

# clean up
stop_shell
rm -f $tmp_file
