#!/bin/bash
#
# simple test with ls to check if the shell can find ls in the PATH

command="ls"
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell
rm -f $tmp_file

# create a pseudo random file
touch $tmp_file

# empty PATH
OLDPATH="$PATH"
PATH="/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/usr/games:/usr/local/games:"
# send commands
echo "$command" | $SHELL > $OUTPUTFILE 2> /dev/null &

# put PATH back
PATH="$OLDPATH"

# wait a little bit
$SLEEP $SLEEPSECONDS

# copy saved output for debugging
# cat $OUTPUTFILE > "/home/vagrant/simple_shell/simple_shell_test_suite/your_output"

# check the result
nmatch=`cat $OUTPUTFILE | grep -c "$tmp_file"`
if [ $nmatch -eq 1 ]; then
	   print_ok
else
	   print_ko
fi

# clean up
stop_shell
rm -f $tmp_file
